---
version: 1
disable_existing_loggers: False
formatters:
  simple:
    format: '[%(levelname)s] [%(asctime)s] [%(name)s] %(message)s'

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: simple
    stream: ext://sys.stdout

  file_handler:
    class: logging.FileHandler
    level: DEBUG
    formatter: simple
    filename: DB-GPT.log

loggers:
  matplotlib.font_manager:
    level: INFO
    handlers: [ console, file_handler ]
    propagate: False

  httpcore:
    level: INFO
    handlers: [ console, file_handler ]
    propagate: False

  openai._base_client:
    level: INFO
    handlers: [ console, file_handler ]
    propagate: False

  httpx:
    level: WARNING
    handlers: [ console, file_handler ]
    propagate: False

  numexpr:
    level: WARNING
    handlers: [ console, file_handler ]
    propagate: False

root:
  level: DEBUG
  handlers: [console, file_handler]
